trainingInput:
    scaleTier: CUSTOM
    masterType: standard
    workerType: standard
    parameterServerType: standard
    workerCount: 5
    parameterServerCount: 1
#    hyperparameters:
#      goal: MAXIMIZE
#      hyperparameterMetricTag: hp_auc
#      maxTrials: 50
#      maxParallelTrials: 2
#      params:
#        - parameterName: embedding-size
#          type: INTEGER
#          minValue: 5
#          maxValue: 10
#          scaleType: UNIT_LINEAR_SCALE
#        - parameterName: first-layer-size
#          type: INTEGER
#          minValue: 50
#          maxValue: 100
#          scaleType: UNIT_LINEAR_SCALE
